### ISSUE TITLE
type RegressionResultFE has no field df_residual

### ISSUE THREAD

**Issue by Asquidy** [eloualiche/FixedEffectjlr#3]
Hi, thanks for creating this package! I was trying to call FixedEffectsModels.jl from R and got the following error:
"type RegressionResultFE has no field df_residual
Stacktrace:
 [1] getproperty(::Any, ::Symbol) at ./sysimg.jl:18
 [2] top-level scope at none:0
" 
I think this may occur because FixedEffectsModels changed the interface. Here is a warning message FixedEffectModels.jl/src/RegressionResult.jl

I think replacing df_residual with dof_residual should work, but wanted to get your thoughts. 
"
function df_residual(x::AbstractRegressionResult)
    Base.depwarn("df_residual is deprecated. Use dof_residual", :Source)
    dof_residual(x)
end
"

**Comment by eloualiche** [comment]
thanks for the tip. I changed the syntax from df to dof. 
let me know if it works.

 which version of julia are you running?

**Comment by Asquidy** [comment]
Thanks, it worked! I'm using 1.0.1
